# fly.toml app configuration file generated for sjp-frontend-teste on 2024-11-06T23:26:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sjp-frontend-teste'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
